[build]
  command = "npm run build"  # Replace with your build command if needed
  functions = "netlify-functions"  # Specify the directory where your serverless functions are located
  publish = "public"  # Specify the directory containing your static files (HTML, CSS, JS)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  # Define headers for your site if needed
